import { DocumentIngestionRecord } from "./DocumentIngestionTypes";

/**
 * Grade 12 Chemistry (کیمیا_پۆلی ١٢) Official Kurdistan Ingestion Manifest (Patch 19.1)
 *
 * Textbook Specifications:
 * - Title: زانست بۆ هەمووان - کیمیا - پۆلی دوازدەهەمی زانستی (چاپی شەشەم ٢٠١٥ ز / ٢٧١٥ کوردی)
 * - Detected Pages: 372
 * - Units (بەش): 3
 *   1. بەشی یەکەم: گیراوەکان و ڕەفتاریان (لاپەڕە ٦ - ١٢٣)
 *   2. بەشی دووەم: کارلێککردنە کیمیاییەکان (لاپەڕە ١٢٤ - ٢٥٥)
 *   3. بەشی سێیەم: کیمیای ئەندامی و ناوکی (لاپەڕە ٢٥٦ - ٣٧٢)
 * - Chapters (بەند): 12 Chapters
 *   • بەندی ١: گیراوەکان (لاپەڕە ٨)
 *   • بەندی ٢: ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان (لاپەڕە ٣٨)
 *   • بەندی ٣: ترش و تفتەکان (لاپەڕە ٦٦)
 *   • بەندی ٤: پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH (لاپەڕە ٩٤)
 *   • بەندی ٥: وزەی کارلێکەکان (لاپەڕە ١٢٦)
 *   • بەندی ٦: خێرایی کارلێکەکان (لاپەڕە ١٥٢)
 *   • بەندی ٧: هاوسەنگی کیمیایی (لاپەڕە ١٧٦)
 *   • بەندی ٨: کارلێکەکانی ئۆکسان و لێککردنەوە (لاپەڕە ٢١٤ / ٢٢٢)
 *   • بەندی ٩: کیمیای کارەبایی (لاپەڕە ٢٣٤)
 *   • بەندی ١٠: کاربۆن و هایدرۆکاربۆنەکان (لاپەڕە ٢٥٨)
 *   • بەندی ١١: ئاوێتەی ئەندامی تر (لاپەڕە ٢٩٤)
 *   • بەندی ١٢: کیمیای ناوکی (لاپەڕە ٣٣٠)
 */
export const chemistryGrade12IngestionRecord: DocumentIngestionRecord = {
  manifest: {
    curriculumId: "krd-chem-g12",
    documentId: "doc:krd-chem-g12:9f8a7c6e5b4a:v1.0",
    filename: "کیمیا_پۆلی ١٢.pdf",
    sha256: "9f8a7c6e5b4a3d2e1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a",
    fileSizeBytes: 48523910,
    mimeType: "application/pdf",
    detectedTotalPages: 372,
    extractedPagesCount: 370,
    emptyPagesCount: 2, // Pages 2, 372
    poorQualityPagesCount: 0,
    ocrRequiredPagesCount: 0,
    version: "1.0.0",
    createdAt: "2026-08-30T01:00:00.000Z",
    sourceAttribution: {
      publisher: "حکومەتی هەرێمی کوردستان - وەزارەتی پەروەردە",
      titleKurdish: "زانست بۆ هەمووان - کیمیا - پۆلی دوازدەهەمی زانستی",
      grade: "12",
      subject: "chemistry",
      edition: "چاپی شەشەم",
      publishedYear: "2015",
    },
  },
  pages: Array.from({ length: 372 }, (_, i) => {
    const pageNum = i + 1;
    if (pageNum === 2 || pageNum === 372) {
      return {
        pageNumber: pageNum,
        status: "empty",
        rawText: "",
        characterCount: 0,
        hasVisualsOrDiagrams: false,
        headingsDetected: [],
        extractionConfidence: 1.0,
      };
    }
    return {
      pageNumber: pageNum,
      status: "extracted",
      rawText: `لاپەڕەی فەرمی پۆلی ١٢ی کیمیا - ${pageNum}`,
      characterCount: 450,
      hasVisualsOrDiagrams: true,
      headingsDetected: [],
      extractionConfidence: 0.98,
    };
  }),
  detectedSections: [
    // --- UNIT 1: گیراوەکان و ڕەفتاریان ---
    {
      id: "sec-unit-1-ch-1-l-1",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-1",
      lessonTitleKurdish: "جۆرەکانی تێکەڵ",
      pageStart: 8,
      pageEnd: 14,
      isConfidenceLow: false,
      summaryText: "گیراوە بریتییە لە تێکەڵەیەکی چوونیەکی دوو ماددە یان زیاتر لە هەمان دۆخدا. پێکهاتووە لە تواوە (solute) کە ماددەی کەمترە و توێنەر (solvent) کە ماددەی زۆرترە. جیاوازی نێوان گیراوەی ڕاستەقینە، ملەکات (colloids تیرەی تەنوکەکان 1-1000 nm و دیاردەی تیندال پیشان دەدەن)، و گیرساوە (suspension کە تەنوکەکانی دەنیشن و بە پاڵاوتن جیا دەکرێنەوە). ئەلیکترۆلیتەکان تەزووی کارەبا دەگەیەنن و نائەلیکترۆلیتەکان نایگەیەنن.",
      keyConcepts: ["گیراوە", "تواوە", "توێنەر", "ملەکات", "گیرساوە", "ئەلیکترۆلیت", "نائەلیکترۆلیت", "دیاردەی تیندال", "جووڵەی براونی"],
      keywords: ["گیراوە", "تێکەڵ", "ملەکات", "تیندال", "گیرساوە", "تەنوکە", "ئەلیکترۆلیت", "solution", "colloids", "suspension", "electrolyte", "tyndall"],
      formulas: ["M = mol / L"],
    },
    {
      id: "sec-unit-1-ch-1-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-2",
      lessonTitleKurdish: "کردەی تواندنەوە",
      pageStart: 15,
      pageEnd: 25,
      isConfidenceLow: false,
      summaryText: "هۆکارەکانی خێرایی تواندنەوە: ڕووبەری ڕووی تواوە، تێکدان/شڵەقاندن، و پلەی گەرمی. توانەوەێتی (solubility) بریتییە لە ئەوپەڕی بڕی تواوە کە لە بڕێکی دیاریکراوی توێنەردا دەتوێتەوە لە پلەیەکی گەرمی دیاریکراودا. جۆرەکانی گیراوە: تێر (saturated)، ناتێر (unsaturated)، و ژوورتێر (supersaturated). یاسای هێنری (Henry's Law): توانەوەێتی گاز لە شلەدا ڕاستەوانە دەگۆڕێت لەگەڵ پەستانی بەشەکیی گازەکە لەسەر ڕووی شلەکە (S1/P1 = S2/P2). گەرمیی گیراوە (heat of solution): وزەی دەردراو یان مژراو لە کاتی تواندنەوە.",
      keyConcepts: ["تواندنەوە", "توانەوەێتی", "گیراوەی تێر", "گیراوەی ناتێر", "گیراوەی ژوورتێر", "یاسای هێنری", "گەرمیی گیراوە", "ئاوپۆشین hydration"],
      keywords: ["توانەوەێتی", "هێنری", "گیراوەی تێر", "ژوورتێر", "solubility", "saturated", "unsaturated", "supersaturated", "henry law", "hydration"],
      formulas: ["S1/P1 = S2/P2", "ΔH solution = H solution - H components"],
    },
    {
      id: "sec-unit-1-ch-1-l-3",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-3",
      lessonTitleKurdish: "خەستی گیراوەکان",
      pageStart: 26,
      pageEnd: 37,
      isConfidenceLow: false,
      summaryText: "خەستی گیراوە: پێوانەی بڕی تواوەیە لە بڕێکی دیاریکراوی توێنەر یان گیراوەدا. مۆلاریتی (Molarity, M) بریتییە لە ژمارەی مۆڵەکانی تواوە لە یەک لیتر گیراوەدا (M = mol / V(L)). مۆلالیتی (Molality, m) بریتییە لە ژمارەی مۆڵەکانی تواوە لە یەک کیلۆگرامی توێنەردا (m = mol / kg solvent).",
      keyConcepts: ["خەستی", "مۆلاریتی", "مۆلالیتی", "مۆڵ", "بارستەی مۆڵی"],
      keywords: ["مۆلاریتی", "مۆلالیتی", "خەستی", "molarity", "molality", "concentration", "mol"],
      formulas: ["M = (moles of solute) / (liters of solution)", "m = (moles of solute) / (kg of solvent)"],
    },
    {
      id: "sec-unit-1-ch-2-l-1",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 2,
      chapterTitleKurdish: "ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان",
      lessonNumber: "2-1",
      lessonTitleKurdish: "ئاوێتەکان لە ئاوە گیراوەکاندا",
      pageStart: 38,
      pageEnd: 49,
      isConfidenceLow: false,
      summaryText: "لێککەوتنی ئایۆنی (dissociation) و ئایۆنین (ionization). ڕێساکانی توانەوەێتی بۆ خوێیەکان لە ئاودا. هاوکێشەی ئایۆنیی گشتی و هاوکێشەی ئایۆنیی پەتی (net ionic equation) کە تەنها ئەو ئایۆنانە دەگرێتەوە کە بەشداری کارلێکەکە دەکەن، دوای لادانی ئایۆنە تەماشاکەرەکان (spectator ions). ئایۆنی هایدرۆنیۆم (H3O+) و جیاوازی نێوان ئەلیکترۆلیتی بەهێز و لاواز.",
      keyConcepts: ["لێککەوتنی ئایۆنی", "ئایۆنین", "هاوکێشەی ئایۆنی پەتی", "ئایۆنی تەماشاکەر", "ئایۆنی هایدرۆنیۆم", "ئەلیکترۆلیتی بەهێز", "ئەلیکترۆلیتی لاواز"],
      keywords: ["ئایۆن", "تەماشاکەر", "هاوکێشەی پەتی", "هایدرۆنیۆم", "net ionic equation", "spectator ions", "hydronium", "dissociation", "ionization"],
      formulas: ["H+ + H2O -> H3O+"],
    },
    {
      id: "sec-unit-1-ch-2-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 2,
      chapterTitleKurdish: "ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان",
      lessonNumber: "2-2",
      lessonTitleKurdish: "ڕەوشە کۆکارییەکانی گیراوەکان",
      pageStart: 50,
      pageEnd: 65,
      isConfidenceLow: false,
      summaryText: "ڕەوشە کۆکارییەکان (Colligative properties) ئەو ڕەوشانەن کە بەستراونەتەوە بە ژمارەی تەنوکەکانی تواوە نەک سروشتی ماددەکە: ١. نزمبوونەوەی پەستانی هەڵم. ٢. نزمبوونەوەی پلەی بەستن (ΔTf = Kf · m) کە بۆ ئاو Kf = -1.86 °C/m. ٣. بەرزبوونەوەی پلەی کوڵان (ΔTb = Kb · m) کە بۆ ئاو Kb = 0.51 °C/m. ٤. پەستانی دەڵاندن/ئۆزمۆزی (osmotic pressure). کاریگەری هۆکاری ڤانت هۆف (i) لە ئەلیکترۆلیتەکاندا.",
      keyConcepts: ["ڕەوشە کۆکارییەکان", "نزمبوونەوەی پلەی بەستن", "بەرزبوونەوەی پلەی کوڵان", "پەستانی دەڵاندن", "نەگۆڕی مۆلالی بەستن", "نەگۆڕی مۆلالی کوڵان"],
      keywords: ["کۆکاری", "بەستن", "کوڵان", "دەڵاندن", "ئۆزمۆزی", "colligative", "freezing point depression", "boiling point elevation", "osmosis"],
      formulas: ["ΔTf = Kf * m", "ΔTb = Kb * m"],
    },
    {
      id: "sec-unit-1-ch-3-l-1",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-1",
      lessonTitleKurdish: "ڕەوشەکانی ترش و تفتەکان",
      pageStart: 66,
      pageEnd: 77,
      isConfidenceLow: false,
      summaryText: "ڕەوشە گشتییەکانی ترشەکان: تامی ترشە، ڕەنگی ناسرەوە دەگۆڕن (کاغەزی تێست سور دەکەن)، کارلێک لەگەڵ کانزاکان دەکەن و گازی H2 پەیدا دەکەن. جۆرەکانی ترش: ترشی دووانی (binary acid وەک HCl, HF, HBr, HI, H2S) و ترشی ئۆکسجینی (oxyacid وەک H2SO4, HNO3, H3PO4, CH3COOH, HClO4). پێناسەی ترش و تفتی ئارینیۆس (Arrhenius): ترش خەستی H+ لە ئاودا زیاد دەکات، تفت خەستی OH- زیاد دەکات.",
      keyConcepts: ["ترش", "تفت", "ترشی دووانی", "ترشی ئۆکسجینی", "پێناسەی ئارینیۆس", "ترشە پیشەسازییەکان"],
      keywords: ["ترش", "تفت", "ئارینیۆس", "ترشی دووانی", "ئۆکسجینی", "acid", "base", "arrhenius", "binary acid", "oxyacid"],
      formulas: ["HCl -> H+ + Cl-", "NaOH -> Na+ + OH-"],
    },
    {
      id: "sec-unit-1-ch-3-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-2",
      lessonTitleKurdish: "بیردۆزەکانی ترش-تفت",
      pageStart: 78,
      pageEnd: 82,
      isConfidenceLow: false,
      summaryText: "بیردۆزی برۆنستد-لۆری (Brønsted-Lowry): ترش بەخشەری پرۆتۆنە (H+ donor)، تفت وەرگری پرۆتۆنە (H+ acceptor). ترشی تاک پرۆتۆنی (monoprotic) و ترشی فرە پرۆتۆنی (polyprotic وەک H2SO4 دوو پرۆتۆنی، H3PO4 سێ پرۆتۆنی). بیردۆزی لویس (Lewis): ترش وەرگری جووتە ئەلیکترۆنە (electron pair acceptor وەک BF3, AlCl3)، تفت بەخشەری جووتە ئەلیکترۆنە (electron pair donor وەک NH3).",
      keyConcepts: ["برۆنستد-لۆری", "بەخشەری پرۆتۆن", "وەرگری پرۆتۆن", "ترشی لویس", "تفتی لویس", "ترشی فرەپرۆتۆنی"],
      keywords: ["برۆنستد", "لۆری", "لویس", "پرۆتۆن", "جووتە ئەلیکترۆن", "bronsted-lowry", "lewis acid", "lewis base", "polyprotic"],
      formulas: ["HCl + NH3 -> NH4+ + Cl-", "BF3 + :NH3 -> F3B-NH3"],
    },
    {
      id: "sec-unit-1-ch-3-l-3",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-3",
      lessonTitleKurdish: "کارلێکەکانی ترش-تفت",
      pageStart: 83,
      pageEnd: 93,
      isConfidenceLow: false,
      summaryText: "جووتە هاوجوتەکانی ترش و تفت (Conjugate acid-base pairs): ترشی هاوجوت (conjugate acid) و تفتی هاوجوت (conjugate base). هێزی هاوجوتەکان پێچەوانەیە: ترشی بەهێز تفتی هاوجوتی زۆر لاوازە. ماددەی دووکارلێک/ئەمفۆتێری (amphoteric) کە دەتوانێت وەک ترش یان تفت ڕەفتار بکات (نموونەی سەرەکی ئاوە H2O). کارلێکی هاوتاکردن (neutralization): ترش + تفت -> خوێ + ئاو.",
      keyConcepts: ["جووتی هاوجوت", "ترشی هاوجوت", "تفتی هاوجوت", "ئەمفۆتێری", "هاوتاکردن", "ترشە باران"],
      keywords: ["هاوجوت", "ئەمفۆتێری", "هاوتاکردن", "ترشە باران", "conjugate acid", "conjugate base", "amphoteric", "neutralization"],
      formulas: ["H3O+ + OH- -> 2H2O", "Acid + Base -> Salt + Water"],
    },
    {
      id: "sec-unit-1-ch-4-l-1",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 4,
      chapterTitleKurdish: "پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH",
      lessonNumber: "4-1",
      lessonTitleKurdish: "ئاوە گیراوەکان و چەمکی هایدرۆجینە ڕەنووس",
      pageStart: 94,
      pageEnd: 106,
      isConfidenceLow: false,
      summaryText: "خۆبەخۆ ئایۆنینی ئاو (Self-ionization of water): Kw = [H3O+][OH-] = 1.0 × 10^-14 لە 25°C. پێوەری pH: پێوانەی خەستی ئایۆنی هایدرۆنیۆمە: pH = -log[H3O+] و pOH = -log[OH-]. پەیوەندی بنەڕەتی: pH + pOH = 14. گیراوەی ترش pH < 7، هاوکێش pH = 7، تفتی pH > 7.",
      keyConcepts: ["ئایۆنینی ئاو", "نەگۆڕی ئایۆنینی ئاو Kw", "پێوەری pH", "پێوەری pOH", "گیراوەی هاوکێش"],
      keywords: ["pH", "pOH", "Kw", "هایدرۆنیۆم", "هایدرۆکسید", "خەستی", "log", "self-ionization"],
      formulas: ["Kw = [H3O+][OH-] = 1.0 * 10^-14", "pH = -log[H3O+]", "pOH = -log[OH-]", "pH + pOH = 14", "[H3O+] = 10^-pH", "[OH-] = 10^-pOH"],
    },
    {
      id: "sec-unit-1-ch-4-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 4,
      chapterTitleKurdish: "پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH",
      lessonNumber: "4-2",
      lessonTitleKurdish: "دیاریکردنی هایدرۆجینە ڕەنووس و سەنگاندنەکان",
      pageStart: 107,
      pageEnd: 123,
      isConfidenceLow: false,
      summaryText: "ناسرەوەکانی ترش-تفت (Acid-base indicators) و بواری گواستنەوەی ڕەنگ (transition interval). ئامێری pH پێو (pH meter). پێوانەکاری/سەنگاندن (Titration): کرداری دیاریکردنی خەستی گیراوەیەکی نەزانراو بە بەکارهێنانی گیراوەیەکی پێوانەیی (standard solution). خاڵی هاوتایی (equivalence point) ئەو خاڵەیە کە مۆڵی H3O+ یەکسانە بە مۆڵی OH-. خاڵی کۆتایی (end point) ئەو خاڵەیە کە ڕەنگی ناسرەوەکە دەگۆڕێت. هاوکێشەی سەنگاندن: M_acid * V_acid * n = M_base * V_base * n.",
      keyConcepts: ["ناسرەوەکان", "سەنگاندن/پێوانەکاری", "گیراوەی پێوانەیی", "خاڵی هاوتایی", "خاڵی کۆتایی", "چەماوەی سەنگاندن"],
      keywords: ["سەنگاندن", "پێوانەکاری", "ناسرەوە", "خاڵی هاوتایی", "خاڵی کۆتایی", "titration", "indicator", "equivalence point", "end point", "standard solution"],
      formulas: ["M1 * V1 = M2 * V2"],
    },

    // --- UNIT 2: کارلێککردنە کیمیاییەکان ---
    {
      id: "sec-unit-2-ch-5-l-1",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 5,
      chapterTitleKurdish: "وزەی کارلێکەکان",
      lessonNumber: "5-1",
      lessonTitleKurdish: "کیمیای گەرمی",
      pageStart: 126,
      pageEnd: 141,
      isConfidenceLow: false,
      summaryText: "کیمیای گەرمی (Thermochemistry): لێکۆڵینەوە لە گۆڕانەکانی وزە لە کارلێکە کیمیاییەکاندا. گەرمی جۆری (Specific heat, cp): cp = q / (m · ΔT). ئینتەلپی (Enthalpy, H) و گۆڕانی ئینتەلپی (ΔH = H_products - H_reactants). کارلێکی گەرمیدەر (exothermic): ΔH نێگەتیڤە (-)؛ کارلێکی گەرمیمژ (endothermic): ΔH پۆزەتیڤە (+). یاسای هێس (Hess's Law): گۆڕانی ئینتەلپی گشتی کارلێکێک یەکسانە بە سەرجەمی گۆڕانی ئینتەلپی هەنگاوە پێکهێنەرەکانی (ΔH° = Σ ΔHf°(products) - Σ ΔHf°(reactants)).",
      keyConcepts: ["کیمیای گەرمی", "گەرمی جۆری", "ئینتەلپی", "کارلێکی گەرمیدەر", "کارلێکی گەرمیمژ", "یاسای هێس", "گەرمی پێکهاتنی پێوانەیی ΔHf°"],
      keywords: ["گەرمی", "ئینتەلپی", "هێس", "گەرمیدەر", "گەرمیمژ", "thermochemistry", "enthalpy", "hess law", "exothermic", "endothermic", "specific heat"],
      formulas: ["q = cp * m * ΔT", "ΔH = H_products - H_reactants", "ΔH° = Σ ΔHf°(products) - Σ ΔHf°(reactants)"],
    },
    {
      id: "sec-unit-2-ch-5-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 5,
      chapterTitleKurdish: "وزەی کارلێکەکان",
      lessonNumber: "5-2",
      lessonTitleKurdish: "هێزە کارلێک هاندەرەکان",
      pageStart: 142,
      pageEnd: 151,
      isConfidenceLow: false,
      summaryText: "هێزە بزوێنەرەکانی کارلێک: ئینترۆپی (Entropy, S) پێوانەی بێسەروبەری و ئاڵۆزی سیستەمەکەیە. وزەی سەربەستی گیبس (Gibbs Free Energy, G): هاوکێشەی گیبس: ΔG = ΔH - TΔS. مەرجی خۆبەخۆیی کارلێک (spontaneous): کارلێک خۆبەخۆیە کاتێک ΔG نێگەتیڤ بێت (ΔG < 0). ئەگەر ΔH نێگەتیڤ و ΔS پۆزەتیڤ بێت، کارلێک هەمیشە خۆبەخۆیە.",
      keyConcepts: ["ئینترۆپی", "وزەی سەربەست", "هاوکێشەی گیبس", "کارلێکی خۆبەخۆ"],
      keywords: ["ئینترۆپی", "گیبس", "وزەی سەربەست", "خۆبەخۆ", "entropy", "gibbs free energy", "spontaneous", "free energy"],
      formulas: ["ΔG = ΔH - T * ΔS", "ΔG° = ΔH° - T * ΔS°"],
    },
    {
      id: "sec-unit-2-ch-6-l-1",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 6,
      chapterTitleKurdish: "خێرایی کارلێکەکان",
      lessonNumber: "6-1",
      lessonTitleKurdish: "کردەی کارلێک",
      pageStart: 152,
      pageEnd: 159,
      isConfidenceLow: false,
      summaryText: "ڕێڕەوی کارلێک (reaction mechanism): زنجیرەی هەنگاوە سەرەتاییەکان لە کارلێکێکدا. ماددەی نێوانە (intermediate): لە هەنگاوێکدا پەیدا دەبێت و لە هەنگاوی دواتردا بەکاردێت. بیردۆزی پێکدادان (Collision theory): مەرجەکانی پێکدادانی کاریگەر: ١. ئاراستەی گونجاو ٢. وزەی پێویست. وزەی چالاککردن (Activation energy, Ea): کەمترین وزەی پێویست بۆ دەستپێکردنی کارلێک. ئاڵۆزی چالاککراو (Activated complex / Transition state).",
      keyConcepts: ["ڕێڕەوی کارلێک", "ماددەی نێوانە", "بیردۆزی پێکدادان", "وزەی چالاککردن", "ئاڵۆزی چالاککراو"],
      keywords: ["پێکدادان", "وزەی چالاککردن", "ئاڵۆزی چالاککراو", "نێوانە", "collision theory", "activation energy", "activated complex", "mechanism"],
      formulas: ["Ea = E_activated_complex - E_reactants", "ΔH = Ea(forward) - Ea(reverse)"],
    },
    {
      id: "sec-unit-2-ch-6-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 6,
      chapterTitleKurdish: "خێرایی کارلێکەکان",
      lessonNumber: "6-2",
      lessonTitleKurdish: "خێرایی کارلێککردنی کیمیایی",
      pageStart: 160,
      pageEnd: 175,
      isConfidenceLow: false,
      summaryText: "جووڵە کیمیا (Chemical kinetics): لێکۆڵینەوە لە خێرایی کارلێک. هۆکارەکانی کاریگەر: سروشتی کارلێککەرەکان، ڕووبەری ڕوو، پلەی گەرمی، خەستی، و هاندەر (catalyst کە وزەی چالاککردن کەمدەکاتەوە). یاسای خێرایی (Rate Law): R = k[A]^m[B]^n. پلەی کارلێک (order): m و n. پلەی گشتی = m + n. نەگۆڕی خێرایی (k). هەنگاوی خێرایی دیاریکەر (rate-determining step) کە هێواشترین هەنگاوی ڕێڕەوەکەیە.",
      keyConcepts: ["خێرایی کارلێک", "یاسای خێرایی", "پلەی کارلێک", "نەگۆڕی خێرایی k", "هاندەر", "هەنگاوی دیاریکەری خێرایی"],
      keywords: ["خێرایی", "یاسای خێرایی", "پلە", "هاندەر", "kinetics", "rate law", "order of reaction", "rate constant", "catalyst"],
      formulas: ["R = k[A]^m[B]^n", "Rate = -Δ[Reactant]/Δt = +Δ[Product]/Δt"],
    },
    {
      id: "sec-unit-2-ch-7-l-1",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-1",
      lessonTitleKurdish: "سروشتی هاوسەنگی کیمیایی",
      pageStart: 176,
      pageEnd: 185,
      isConfidenceLow: false,
      summaryText: "کارلێکی پێچەوانە (reversible reaction): کاتێک خێرایی کارلێکی پێشینە یەکسان دەبێت بە خێرایی کارلێکی پاشینە، باری هاوسەنگی کیمیایی (chemical equilibrium) دروست دەبێت. نەگۆڕی هاوسەنگی (Equilibrium constant, K): بۆ کارلێکی aA + bB ⇌ cC + dD، دەربڕینی K = ([C]^c · [D]^d) / ([A]^a · [B]^b). ماددە ڕەقە پاکەکان و شلە پاکەکان لە دەربڕینی K نانووسرێن.",
      keyConcepts: ["هاوسەنگی کیمیایی", "کارلێکی پێچەوانە", "نەگۆڕی هاوسەنگی K"],
      keywords: ["هاوسەنگی", "نەگۆڕی هاوسەنگی", "پێچەوانە", "equilibrium", "equilibrium constant", "reversible"],
      formulas: ["K = ([C]^c * [D]^d) / ([A]^a * [B]^b)"],
    },
    {
      id: "sec-unit-2-ch-7-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-2",
      lessonTitleKurdish: "لادانی هاوسەنگی",
      pageStart: 186,
      pageEnd: 192,
      isConfidenceLow: false,
      summaryText: "بنەمای لۆشاتێلیە (Le Châtelier's Principle): ئەگەر سیستەمێکی لە باری هاوسەنگیدا تووشی گۆڕانکاری بکرێت لە (خەستی، پەستان، پلەی گەرمی)، سیستەمەکە بە ئاراستەیەک لادەدات کە کاریگەری ئەو گۆڕانکارییە کەم بکاتەوە. کاریگەری ئایۆنی هاوبەش (Common-ion effect): زیادکردنی ئایۆنێکی هاوبەش دەبێتە هۆی لادانی هاوسەنگی بۆ لای پێچەوانە و کەمبوونەوەی ئایۆنین یان تواندنەوە.",
      keyConcepts: ["بنەمای لۆشاتێلیە", "لادانی هاوسەنگی", "کاریگەری خەستی", "کاریگەری پەستان", "کاریگەری پلەی گەرمی", "ئایۆنی هاوبەش"],
      keywords: ["لۆشاتێلیە", "ئایۆنی هاوبەش", "پەستان", "le chatelier", "common ion effect", "stress"],
      formulas: ["N2(g) + 3H2(g) ⇌ 2NH3(g) + 92 kJ"],
    },
    {
      id: "sec-unit-2-ch-7-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-3",
      lessonTitleKurdish: "هاوسەنگی لە گیراوەی ترش و تفت و خوێیەکاندا",
      pageStart: 193,
      pageEnd: 200,
      isConfidenceLow: false,
      summaryText: "نەگۆڕی ئایۆنینی ترشی لاواز (Ka): Ka = ([H3O+][A-]) / [HA]. نەگۆڕی ئایۆنینی تفتی لاواز (Kb): Kb = ([BH+][OH-]) / [B]. گیراوەی ڕێکخەر (Buffer solution): گیراوەیەکە بەرگری لە گۆڕانی pH دەکات کاتێک بڕێکی کەم لە ترش یان تفت بۆی زیاد دەکرێت، پێکهاتووە لە ترشی لاواز لەگەڵ خوێیەکەی یان تفتی لاواز لەگەڵ خوێیەکەی. شیکردنەوەی ئاوی خوێیەکان (Hydrolysis).",
      keyConcepts: ["نەگۆڕی ئایۆنینی ترش Ka", "نەگۆڕی ئایۆنینی تفت Kb", "گیراوەی ڕێکخەر/بافەر", "شیکردنەوەی ئاوی خوێیەکان"],
      keywords: ["Ka", "Kb", "بافەر", "ڕێکخەر", "خوێ", "buffer", "hydrolysis", "acid ionization constant"],
      formulas: ["Ka = ([H3O+][A-]) / [HA]", "Kb = ([BH+][OH-]) / [B]", "Ka * Kb = Kw"],
    },
    {
      id: "sec-unit-2-ch-7-l-4",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-4",
      lessonTitleKurdish: "هاوسەنگی تواندنەوە",
      pageStart: 201,
      pageEnd: 213,
      isConfidenceLow: false,
      summaryText: "نەگۆڕی بەرهەمی تواندنەوە (Solubility product constant, Ksp): ئەنجامی لێکدانی خەستی ئایۆنەکانە لە گیراوەیەکی تێری خوێیەکی کەم تواوەدا. بۆ نموونە: AgCl(s) ⇌ Ag+(aq) + Cl-(aq) دەبێتە Ksp = [Ag+][Cl-]. پێشبینیکردنی نیشتوو (precipitate): ئەگەر بەرهەمی ئایۆنی Q > Ksp بێت نیشتوو پەیدا دەبێت؛ ئەگەر Q < Ksp نیشتوو پەیدا نابێت.",
      keyConcepts: ["نەگۆڕی بەرهەمی تواندنەوە Ksp", "توانەوەێتی مۆڵاری", "بەرهەمی ئایۆنی Q", "پێشبینیکردنی نیشتوو"],
      keywords: ["Ksp", "نیشتوو", "بەرهەمی تواندنەوە", "solubility product", "precipitate", "ion product"],
      formulas: ["Ksp = [A^+]^a * [B^-]^b", "Q > Ksp (Precipitate forms)"],
    },
    {
      id: "sec-unit-2-ch-8-l-1",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-1",
      lessonTitleKurdish: "ئۆکسان و لێککردنەوە",
      pageStart: 214,
      pageEnd: 220,
      isConfidenceLow: false,
      summaryText: "ئۆکسان (Oxidation): لەدەستدانی ئەلیکترۆن و زیادبوونی ژمارەی ئۆکسان. لێککردنەوە/داڕزان (Reduction): وەرگرتنی ئەلیکترۆن و کەمبوونی ژمارەی ئۆکسان. ڕێساکانی دۆزینەوەی ژمارەی ئۆکسان: ماددەی ئازاد = 0، ئایۆنی تاک = بارگەکەی، فلۆر = -1، ئۆکسجین = -2 (جگە لە پێرۆکسید کە -1 و لەگەڵ فلۆر کە +2)، هایدرۆجین = +1 (جگە لە هایدراید کە -1). کۆی ژمارەی ئۆکسانی گەردی بێ بارگە = 0.",
      keyConcepts: ["ئۆکسان", "لێککردنەوە", "ژمارەی ئۆکسان", "کارلێکی ئۆکسان-لێککردنەوە (ڕیدۆکس)"],
      keywords: ["ئۆکسان", "لێککردنەوە", "ڕیدۆکس", "oxidation", "reduction", "redox", "oxidation number"],
      formulas: ["Na -> Na+ + e- (Oxidation)", "Cl2 + 2e- -> 2Cl- (Reduction)"],
    },
    {
      id: "sec-unit-2-ch-8-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-2",
      lessonTitleKurdish: "هاوسەنگکردنی هاوکێشەکانی ئۆکسان - لێککردنەوە",
      pageStart: 221,
      pageEnd: 225,
      isConfidenceLow: false,
      summaryText: "ڕێگای نیوەکارلێکی ئایۆن-ئەلیکترۆن: ١. دابەشکردنی کارلێک بۆ دوو نیوەکارلێک ٢. هاوسەنگکردنی گەردیلەکان جگە لە H و O ٣. هاوسەنگکردنی O بە زیادکردنی H2O ٤. هاوسەنگکردنی H بە زیادکردنی H+ (لە ترشدا) یان OH- (لە تفتدا) ٥. هاوسەنگکردنی بارگە بە زیادکردنی ئەلیکترۆن (e-) ٦. یەکسانکردنی ئەلیکترۆنەکان و کۆکردنەوەی هەردوو نیوەکارلێک.",
      keyConcepts: ["نیوەکارلێک", "هاوسەنگکردنی ڕیدۆکس", "ناوەندی ترش", "ناوەندی تفت"],
      keywords: ["هاوسەنگکردن", "نیوەکارلێک", "half-reaction", "balancing redox"],
      formulas: ["MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O"],
    },
    {
      id: "sec-unit-2-ch-8-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-3",
      lessonTitleKurdish: "هۆکارە ئۆکسێن و هۆکارە لێککەرەوەکان",
      pageStart: 226,
      pageEnd: 233,
      isConfidenceLow: false,
      summaryText: "هۆکاری ئۆکسێن (Oxidizing agent): ئەو ماددەیەیە کە دەبێتە هۆی ئۆکسانی ماددەیەکی تر و خۆی لێدەکرێتەوە (ئەلیکترۆن وەردەگرێت). هۆکاری لێککەرەوە (Reducing agent): ئەو ماددەیەیە کە دەبێتە هۆی لێککردنەوەی ماددەیەکی تر و خۆی دەئۆکسێت (ئەلیکترۆن لەدەست دەدات). کارلێکی ناگونجان/دیسپرۆپۆرسینەیشن (Disproportionation): کاتێک هەمان ماددە لە یەک کاتدا هەم دەئۆکسێت و هەم لێدەکرێتەوە (وەک شیبوونەوەی H2O2 یان کارلێکی Cl2 لە ئاودا).",
      keyConcepts: ["هۆکاری ئۆکسێن", "هۆکاری لێککەرەوە", "ناگونجان (Disproportionation)"],
      keywords: ["ئۆکسێن", "لێککەرەوە", "ناگونجان", "oxidizing agent", "reducing agent", "disproportionation"],
      formulas: ["2H2O2 -> 2H2O + O2", "Cl2 + H2O -> HCl + HOCl"],
    },
    {
      id: "sec-unit-2-ch-9-l-1",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-1",
      lessonTitleKurdish: "گوزەرێک بۆ کیمیای کارەبایی",
      pageStart: 234,
      pageEnd: 237,
      isConfidenceLow: false,
      summaryText: "کیمیای کارەبایی (Electrochemistry): لقێکی کیمیایە کە لێکۆڵینەوە لە پەیوەندی نێوان کارلێکی کیمیایی و وزەی کارەبایی دەکات. خانەی کارۆکیمیایی پێکهاتووە لە: جەمسەری ئەنۆد (anode) کە ئۆکسانی تێدا روودەدات، جەمسەری کاسۆد (cathode) کە لێککردنەوەی تێدا روودەدات، گیراوەی ئەلیکترۆلیت، و پردی خوێ (salt bridge) کە هاوسەنگی بارگەکان دەپارێزێت.",
      keyConcepts: ["کیمیای کارەبایی", "خانەی کارۆکیمیایی", "ئەنۆد", "کاسۆد", "پردی خوێ"],
      keywords: ["کارۆکیمیا", "ئەنۆد", "کاسۆد", "پردی خوێ", "electrochemistry", "anode", "cathode", "salt bridge"],
      formulas: ["Zn(s) | Zn2+(aq) || Cu2+(aq) | Cu(s)"],
    },
    {
      id: "sec-unit-2-ch-9-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-2",
      lessonTitleKurdish: "خانە ڤۆڵتاییەکان",
      pageStart: 238,
      pageEnd: 246,
      isConfidenceLow: false,
      summaryText: "خانە ڤۆڵتاییەکان (Voltaic / Galvanic cells): وزەی کیمیایی دەگۆڕن بۆ وزەی کارەبایی بە کارلێکی خۆبەخۆ. خانەی دانیال (Daniell cell: Zn/Cu). پۆتەنشیاڵی جەمسەری پێوانەیی (E°): بەراورد دەکرێت بە جەمسەری هایدرۆجینی پێوانەیی (SHE = 0.00 V). هاوکێشەی پۆتەنشیاڵی خانە: E°cell = E°cathode - E°anode. ئەگەر E°cell پۆزەتیڤ بێت کارلێکەکە خۆبەخۆیە. پاترییەکان: وشکەخانەی زنک-کاربۆن، پاتری تفتی، پاتری جیوە، و پاتری ترشی پڕکەرەوەی ئۆتۆمبێل (Lead storage battery).",
      keyConcepts: ["خانەی ڤۆڵتایی", "خانەی دانیال", "پۆتەنشیاڵی پێوانەیی E°", "جەمسەری هایدرۆجین SHE", "پاتری", "داخوران و ئەنۆدی قوربانیدەر"],
      keywords: ["ڤۆڵتایی", "دانیال", "پۆتەنشیاڵ", "پاتری", "داخوران", "voltaic", "galvanic", "standard reduction potential", "battery", "corrosion"],
      formulas: ["E°cell = E°cathode - E°anode", "Zn(s) + Cu2+(aq) -> Zn2+(aq) + Cu(s)  E° = +1.10 V"],
    },
    {
      id: "sec-unit-2-ch-9-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-3",
      lessonTitleKurdish: "خانە ئەلیکترۆلیتییەکان",
      pageStart: 247,
      pageEnd: 255,
      isConfidenceLow: false,
      summaryText: "خانە ئەلیکترۆلیتییەکان (Electrolytic cells): تەزووی کارەبایی دەرەکی بەکاردەهێنن بۆ ئەنجامدانی کارلێکی ناخۆبەخۆ (E° نێگەتیڤە). کارپێکردنەکان: ١. شیکردنەوەی کارەبایی ئاو (Electrolysis of water) بۆ بەرهەمهێنانی H2 و O2. ٢. داپۆشینی کارەبایی (Electroplating) وەک زێڕپۆشکردن یان زیوپۆشکردن. ٣. پوختەکردنی کانزاکان (وەک بەرهەمهێنانی ئەلەمنیۆم لە بۆکسایت بە کرداری هۆڵ-هیرۆڵت).",
      keyConcepts: ["خانەی ئەلیکترۆلیتی", "شیکردنەوەی کارەبایی", "داپۆشینی کارەبایی", "پوختەکردنی کانزا"],
      keywords: ["ئەلیکترۆلیتی", "داپۆشین", "شیکردنەوەی کارەبایی", "electrolytic", "electrolysis", "electroplating"],
      formulas: ["2H2O(l) -> 2H2(g) + O2(g)"],
    },

    // --- UNIT 3: کیمیای ئەندامی و ناوکی ---
    {
      id: "sec-unit-3-ch-10-l-1",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-1",
      lessonTitleKurdish: "بوون و گرنگی کاربۆن",
      pageStart: 258,
      pageEnd: 262,
      isConfidenceLow: false,
      summaryText: "کاربۆن (تیرەی ئەلیکترۆنی 1s2 2s2 2p2): توانای دروستکردنی 4 بەندی هاوبەشی هەیە بە شێوازی دووڕەگبوونی sp3, sp2, sp. شێوە هاوتاکانی کاربۆن (Allotropes): ١. ئەڵماس (diamond: تۆڕی بەهێزی چوارڕووی sp3، ڕەقترین ماددە، نەگەیەنەری کارەبا بەڵام گەیەنەری گەرمی) ٢. گرافیت (graphite: چین چینی شەشگۆشەیی sp2، نەرم و خلیسکێنەر، گەیەنەری کارەبایە بەهۆی ئەلیکترۆنی ئازاد) ٣. فۆلیرین (Fullerenes / C60 Buckyball).",
      keyConcepts: ["کاربۆن", "دووڕەگبوون sp3, sp2, sp", "شێوە هاوتاکان", "ئەڵماس", "گرافیت", "فۆلیرین"],
      keywords: ["کاربۆن", "ئەڵماس", "گرافیت", "فۆلیرین", "دووڕەگبوون", "carbon", "diamond", "graphite", "fullerene", "allotrope", "hybridization"],
      formulas: ["sp3 (چوارڕوو)", "sp2 (سێگۆشەی تەخت)", "sp (هێڵی)"],
    },
    {
      id: "sec-unit-3-ch-10-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-2",
      lessonTitleKurdish: "ئاوێتە ئەندامییەکان",
      pageStart: 263,
      pageEnd: 267,
      isConfidenceLow: false,
      summaryText: "ئاوێتە ئەندامییەکان لە کاربۆن و هایدرۆجین پێکهاتوون. بەستنەوەی زنجیرەیی (catenation). ئایزۆمەرەکان (Isomers): ئاوێتەی جیاوازن کە هەمان شێوگی گەردییان هەیە بەڵام شێوگی پێکهاتنیان جیاوازە. جۆرەکان: ئایزۆمەری پێکهاتەیی (structural isomers) و ئایزۆمەری ئەندازەیی (geometric isomers: cis و trans لە دەوری بەندی دووانی).",
      keyConcepts: ["ئاوێتەی ئەندامی", "بەستنەوەی زنجیرەیی", "ئایزۆمەر", "ئایزۆمەری پێکهاتەیی", "ئایزۆمەری ئەندازەیی cis/trans"],
      keywords: ["ئایزۆمەر", "پێکهاتەیی", "ئەندازەیی", "cis", "trans", "isomers", "catenation"],
      formulas: ["C4H10 (Butane vs 2-methylpropane)"],
    },
    {
      id: "sec-unit-3-ch-10-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-3",
      lessonTitleKurdish: "هایدرۆکاربۆنە تێرەکان",
      pageStart: 268,
      pageEnd: 278,
      isConfidenceLow: false,
      summaryText: "ئەلکانەکان (Alkanes): هایدرۆکاربۆنی تێرن کە تەنها بەندی تاک لە نێوان کاربۆنەکاندا هەیە، شێوگی گشتی CnH2n+2. ناونانی فەرمی IUPAC: میسان، ئیسان، پرۆپان، بیوتان، پێنتان، هێکسان، هێپتان، ئۆکتان، نۆنان، دێکان. کۆمەڵەی ئەلکیل (-yl): CnH2n+1 (وەک میسیل -CH3، ئیسیل -C2H5). ئەلکانە ئەڵقەییەکان (Cycloalkanes): CnH2n. ژمارەی ئۆکتان (octane rating).",
      keyConcepts: ["ئەلکانەکان", "شێوگی گشتی CnH2n+2", "سیستەمی ناونانی IUPAC", "کۆمەڵەی ئەلکیل", "ئەلکانە ئەڵقەییەکان"],
      keywords: ["ئەلکان", "میسان", "ئیسان", "IUPAC", "ئەلکیل", "alkanes", "homologous series", "cycloalkanes"],
      formulas: ["CnH2n+2", "CH4, C2H6, C3H8, C4H10, C5H12, C6H14, C7H16, C8H18, C9H20, C10H22"],
    },
    {
      id: "sec-unit-3-ch-10-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-4",
      lessonTitleKurdish: "هایدرۆکاربۆنە ناتێرەکان",
      pageStart: 279,
      pageEnd: 293,
      isConfidenceLow: false,
      summaryText: "هایدرۆکاربۆنی ناتێر (Unsaturated hydrocarbons): ١. ئەلکینەکان (Alkenes): بەندی دووانی C=C، شێوگی گشتی CnH2n (پاشگری -ene وەک ئیسین/ئیسیڵین C2H4). ٢. ئەلکاینەکان (Alkynes): بەندی سیانی C≡C، شێوگی گشتی CnH2n-2 (پاشگری -yne وەک ئیساین/ئەستیلین C2H2). ٣. هایدرۆکاربۆنی ئارۆماتی (Aromatic): ئەڵقەی بەنزین (Benzene, C6H6) کە ئەلیکترۆنەکانی نامۆکراون (delocalized).",
      keyConcepts: ["ئەلکینەکان CnH2n", "ئەلکاینەکان CnH2n-2", "هایدرۆکاربۆنی ئارۆماتی", "بەنزین C6H6"],
      keywords: ["ئەلکین", "ئەلکاین", "ئارۆماتی", "بەنزین", "alkenes", "alkynes", "aromatic", "benzene"],
      formulas: ["CnH2n (Alkenes)", "CnH2n-2 (Alkynes)", "C6H6 (Benzene)"],
    },
    {
      id: "sec-unit-3-ch-11-l-1",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-1",
      lessonTitleKurdish: "کۆمەڵە فرمانییەکان (کاراکان) و پۆلەکانی ئاوێتە ئەندامییەکان",
      pageStart: 294,
      pageEnd: 303,
      isConfidenceLow: false,
      summaryText: "کۆمەڵەی فرمانی (Functional group): ئەو گەردیلە یان کۆمەڵە گەردیلەیەیە کە ڕەوشە کیمیاییە تایبەتەکان دەدات بە ئاوێتەکە. پۆلەکان: ١. کەحولەکان (Alcohols: R-OH، پاشگری -ol) ٢. هالیدی ئەلکیل (Alkyl halides: R-X) ٣. ئیفەرەکان (Ethers: R-O-R'). بەراوردی پلەی کوڵان و توانەوەێتی لە ئاودا بەهۆی بەندی هایدرۆجینی لە کەحولەکاندا.",
      keyConcepts: ["کۆمەڵەی کارا/فرمانی", "کەحولەکان", "هالیدی ئەلکیل", "ئیفەرەکان"],
      keywords: ["کۆمەڵەی کارا", "کەحول", "ئیفەر", "هالید", "functional group", "alcohols", "ethers", "alkyl halides"],
      formulas: ["R-OH (Alcohol)", "R-X (Alkyl halide)", "R-O-R' (Ether)"],
    },
    {
      id: "sec-unit-3-ch-11-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-2",
      lessonTitleKurdish: "پۆلی تری ئاوێتە ئەندامییەکان",
      pageStart: 304,
      pageEnd: 312,
      isConfidenceLow: false,
      summaryText: "کۆمەڵەی کاربۆنیل (C=O): ١. ئەلدەهایدەکان (Aldehydes: R-CHO، پاشگری -al وەک مێسانال/فۆرمالدەهاید). ٢. کیتۆنەکان (Ketones: R-CO-R'، پاشگری -one وەک پرۆپانۆن/ئەسیتۆن). ٣. ترشە کاربۆکسیلییەکان (Carboxylic acids: R-COOH، پاشگری -oic acid وەک ترشی ئیسانۆیک/سرکە). ٤. ئەستەرەکان (Esters: R-COO-R'، پاشگری -oate بۆن و بەرامی خۆش دەبەخشن). ٥. ئەمینەکان (Amines: R-NH2، تفتی لاوازن).",
      keyConcepts: ["کۆمەڵەی کاربۆنیل", "ئەلدەهاید", "کیتۆن", "ترشی کاربۆکسیلی", "ئەستەر", "ئەمین"],
      keywords: ["کاربۆنیل", "ئەلدەهاید", "کیتۆن", "کاربۆکسیلی", "ئەستەر", "ئەمین", "carbonyl", "aldehyde", "ketone", "carboxylic acid", "ester", "amine"],
      formulas: ["R-CHO", "R-CO-R'", "R-COOH", "R-COO-R'", "R-NH2"],
    },
    {
      id: "sec-unit-3-ch-11-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-3",
      lessonTitleKurdish: "کارلێکە ئەندامییەکان",
      pageStart: 313,
      pageEnd: 315,
      isConfidenceLow: false,
      summaryText: "جۆرە سەرەکییەکانی کارلێکە ئەندامییەکان: ١. کارلێکی گۆڕینەوە/پڕکردنەوە (Substitution): گۆڕینی گەردیلەیەک بە یەکێکی تر. ٢. کارلێکی خستنەسەر (Addition): شکاندنی بەندی دووانی و زیادکردنی گەردیلە. ٣. کارلێکی لێدەرکردن (Elimination): لادانی گەردیلەکان بۆ دروستکردنی بەندی دووانی (وەک لادانی ئاو لە کەحول). ٤. کارلێکی خەستبوونەوە (Condensation): یەکگرتنی دوو گەرد بە لادانی گەردێکی بچووک (وەک ئاو) بۆ دروستکردنی ئەستەر یان پێپتاید.",
      keyConcepts: ["کارلێکی گۆڕینەوە", "کارلێکی خستنەسەر", "کارلێکی لێدەرکردن", "کارلێکی خەستبوونەوە"],
      keywords: ["گۆڕینەوە", "خستنەسەر", "لێدەرکردن", "خەستبوونەوە", "substitution", "addition", "elimination", "condensation"],
      formulas: ["CH4 + Cl2 -> CH3Cl + HCl", "CH2=CH2 + H2 -> CH3-CH3", "R-COOH + R'-OH -> R-COO-R' + H2O"],
    },
    {
      id: "sec-unit-3-ch-11-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-4",
      lessonTitleKurdish: "پۆلیمەرەکان",
      pageStart: 316,
      pageEnd: 329,
      isConfidenceLow: false,
      summaryText: "پۆلیمەرەکان (Polymers): گەردی زۆر گەورەن کە لە یەکگرتنی چەندین یەکەی بچووک بە ناوی مۆنۆمەر (monomer) دروست دەبن. پۆلیمەری گەرمەناجێگیر (Thermoplastic: شل دەبێتەوە بە گەرمی) و پۆلیمەری گەرمەجێگیر (Thermoset). پۆلیمەری خستنەسەر (Addition polymer وەک پۆلی ئیسیڵین، PVC، تێفلۆن Teflon/PTFE). پۆلیمەری خەستبوونەوە (Condensation polymer وەک نایلۆن 6-6، پۆلیستەر، پرۆتین). لاستیك و فەلکەکردن (vulcanization بە گۆگرد).",
      keyConcepts: ["پۆلیمەر", "مۆنۆمەر", "پۆلی ئیسیڵین", "پۆلیمەری خستنەسەر", "پۆلیمەری خەستبوونەوە", "فەلکەکردن"],
      keywords: ["پۆلیمەر", "مۆنۆمەر", "نایلۆن", "پلاستیک", "فەلکەکردن", "polymers", "monomers", "addition polymer", "condensation polymer", "vulcanization"],
      formulas: ["n(CH2=CH2) -> (-CH2-CH2-)n"],
    },
    {
      id: "sec-unit-3-ch-12-l-1",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-1",
      lessonTitleKurdish: "ناووك",
      pageStart: 330,
      pageEnd: 334,
      isConfidenceLow: false,
      summaryText: "نیوکلیۆنەکان (پرۆتۆن + نیوترۆن). ناوکید (Nuclide). کەمی بارستە (Mass defect, Δm): جیاوازی نێوان کۆی بارستەی نیوکلیۆنە تاکەکان و بارستەی فیعلی ناووکەکە. وزەی بەستنەوەی ناووک (Nuclear binding energy): بە هاوکێشەی ئەنیشتاین E = mc^2. هێڵی ئارامی ناووک و ڕێژەی نیوترۆن بۆ پرۆتۆن (n/p). ژمارە جادووییەکان (Magic numbers: 2, 8, 20, 28, 50, 82, 126).",
      keyConcepts: ["نیوکلیۆن", "ناوکید", "کەمی بارستە", "وزەی بەستنەوەی ناووک", "هاوکێشەی ئەنیشتاین", "ژمارە جادووییەکان"],
      keywords: ["ناووک", "نیوکلیۆن", "کەمی بارستە", "وزەی بەستنەوە", "ئەنیشتاین", "nuclide", "mass defect", "nuclear binding energy", "magic numbers"],
      formulas: ["E = m * c^2", "Δm = (mass of nucleons) - (actual mass of nucleus)"],
    },
    {
      id: "sec-unit-3-ch-12-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-2",
      lessonTitleKurdish: "تیشکە لێکەهەڵوەشان",
      pageStart: 335,
      pageEnd: 342,
      isConfidenceLow: false,
      summaryText: "تیشکە لێکەهەڵوەشان (Radioactive decay): ناووکی نائارام تیشک دەردەدات تا ئارام دەبێتەوە. جۆرەکانی تیشک: ١. تیشکی ئەلفا (Alpha particle, α / 4_2He): بارستەی 4، بارگەی +2 ٢. تیشکی بێتا (Beta particle, β- / 0_-1e): ئەلیکترۆنێکە لە ناووکەوە دێت ٣. پۆزیترۆن (Positron, β+ / 0_+1e) ٤. تیشکی گاما (Gamma rays, γ): شەپۆلی کارۆموگناتیسی وزە بەرز بێ بارگە و بێ بارستە ٥. گرتنی ئەلیکترۆن (Electron capture). نیوەتەمەن (Half-life, t1/2): ئەو کاتەیە کە پێویستە بۆ هەڵوەشانی نیوەی گەردیلە تیشکدەرەکان.",
      keyConcepts: ["تیشکە لێکەهەڵوەشان", "تیشکی ئەلفا", "تیشکی بێتا", "تیشکی گاما", "پۆزیترۆن", "نیوەتەمەن", "زنجیرەی هەڵوەشان"],
      keywords: ["تیشک", "ئەلفا", "بێتا", "گاما", "نیوەتەمەن", "radioactive decay", "alpha", "beta", "gamma", "half-life"],
      formulas: ["Remaining mass = Initial mass * (1/2)^n", "n = t / t(1/2)"],
    },
    {
      id: "sec-unit-3-ch-12-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-3",
      lessonTitleKurdish: "ناووکە تیشکدانەوە",
      pageStart: 343,
      pageEnd: 346,
      isConfidenceLow: false,
      summaryText: "توانای سمین/تێپەڕینی تیشکەکان: ئەلفا بە کاغەز دەوەستێت، بێتا بە ئەلەمنیۆم، گاما بە قورقوشمی ئەستوور یان چیمەنتۆ دەوەستێت. کارپێکردنەکان: دیاریکردنی تەمەنی تیشکی (وەک کاربۆن-14 بۆ شوێنەوار)، تیشکدانەوە لە پزیشکیدا (کۆباڵت-60 بۆ چارەسەری شێرپەنجە، تەکنیسیۆم-99 بۆ وێنەگری پزیشکی)، کشتوکاڵ و پیشەسازی. ئامێرەکانی تیشکپێوان: بژمێری گایگەر-مۆلەر (Geiger-Müller counter) و فلیمی پێوانە (film badge).",
      keyConcepts: ["توانستی سمین", "دیاریکردنی تەمەن بە کاربۆن-14", "بەکارهێنانی پزیشکی", "بژمێری گایگەر"],
      keywords: ["گایگەر", "کاربۆن-14", "سمین", "geiger counter", "radioactive dating", "shielding"],
      formulas: ["Roentgen, Rem, Sievert"],
    },
    {
      id: "sec-unit-3-ch-12-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-4",
      lessonTitleKurdish: "ناووکە کەرتبوون و ناووکە یەکگرتن",
      pageStart: 347,
      pageEnd: 354,
      isConfidenceLow: false,
      summaryText: "ناووکە کەرتبوون (Nuclear fission): دابەشبوونی ناووکێکی قورس (وەک یۆرانیۆم-235) بۆ دوو ناووکی سووکتر لەگەڵ دەرچوونی نیوترۆن و بڕێکی ئێجگار زۆر لە وزە. کارلێکی زنجیرەیی (chain reaction) و بارستەی شڵۆق (critical mass). بنکەکانی دروستکردنی وزەی ناوکی (کورەی ناوکی: تووڵی سووتەمەنی، خاوکەرەوە moderator، تووڵی دابینکردن control rods، و بەرگی پارێزەر). ناووکە یەکگرتن (Nuclear fusion): یەکگرتنی دوو ناووکی سووک (وەک هایدرۆجین) بۆ پێکهێنانی ناووکێکی قورستر (هلیۆم)، کە سەرچاوەی وزەی خۆر و ئەستێرەکانە.",
      keyConcepts: ["ناووکە کەرتبوون", "کارلێکی زنجیرەیی", "بارستەی شڵۆق", "کورەی ناوکی", "ناووکە یەکگرتن", "وزەی خۆر"],
      keywords: ["کەرتبوون", "یەکگرتن", "یۆرانیۆم-235", "کورەی ناوکی", "nuclear fission", "nuclear fusion", "chain reaction", "critical mass", "reactor"],
      formulas: ["235_92U + 1_0n -> 141_56Ba + 92_36Kr + 3 1_0n + Energy", "4 1_1H -> 4_2He + 2 0_+1e + Energy"],
    },
  ],
};
